#!/bin/bash
################################################################################
# Deploy Script com Azure Key Vault
################################################################################
set -e

echo "======================================================================"
echo " Data Platform - Deployment com Azure Key Vault"
echo "======================================================================"

# Verificar se Python está disponível
if ! command -v python3 &> /dev/null; then
    echo "❌ ERROR: python3 not found. Please install Python 3."
    exit 1
fi

# Verificar se load_secrets.py existe
if [ ! -f "shared/load_secrets.py" ]; then
    echo "❌ ERROR: shared/load_secrets.py not found"
    exit 1
fi

# Instalar dependências Azure SDK se necessário
echo "Verificando dependências..."
pip3 install -q -r shared/requirements.txt --break-system-packages

# Carregar segredos do Key Vault
echo ""
echo "Carregando segredos do Azure Key Vault..."
echo "----------------------------------------------------------------------"
eval $(python3 shared/load_secrets.py --export)

# Verificar se segredos foram carregados
if [ -z "$POSTGRES_PASSWORD" ]; then
    echo "❌ ERROR: Failed to load secrets from Key Vault"
    exit 1
fi

echo ""
echo "✓ Secrets loaded successfully"
echo ""

# Criar diretórios necessários
echo "Criando diretórios..."
mkdir -p airflow/logs airflow/dags airflow/plugins
mkdir -p superset/config superset/data
mkdir -p postgres/data postgres/init-scripts
mkdir -p shared hop/projects

# Definir permissões (UID 50000 para Airflow)
if [ -d "airflow/logs" ]; then
    echo "Configurando permissões Airflow..."
    sudo chown -R 50000:0 airflow/logs airflow/dags airflow/plugins 2>/dev/null || true
    sudo chmod -R 775 airflow/logs airflow/dags airflow/plugins 2>/dev/null || true
fi

# Fazer backup do .env atual se existir
if [ -f ".env" ]; then
    echo "Fazendo backup de .env → .env.backup.$(date +%Y%m%d_%H%M%S)"
    cp .env ".env.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Criar .env completo com secrets do Key Vault
cat > .env << EOF
# Auto-generated by deploy-keyvault.sh
# Generated: $(date)

COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-data-platform}
TIMEZONE=${TIMEZONE:-America/Sao_Paulo}
PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-bi.bomgado.com.br}

# Azure Key Vault
AZURE_KEYVAULT_URL=https://bomgado-vault.vault.azure.net/

# PostgreSQL (from Key Vault)
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PASSWORD_URLENCODED=${POSTGRES_PASSWORD_URLENCODED}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_AIRFLOW_DB=${POSTGRES_AIRFLOW_DB}
POSTGRES_SUPERSET_DB=${POSTGRES_SUPERSET_DB}

# Redis (from Key Vault)
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_PASSWORD_URLENCODED=${REDIS_PASSWORD_URLENCODED}

# Airflow Secrets (from Key Vault)
AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
AIRFLOW_ADMIN_USERNAME=${AIRFLOW_ADMIN_USERNAME}
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
AIRFLOW_ADMIN_FIRSTNAME=${AIRFLOW_ADMIN_FIRSTNAME}
AIRFLOW_ADMIN_LASTNAME=${AIRFLOW_ADMIN_LASTNAME}
AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL}

# Superset Secrets (from Key Vault)
SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
SUPERSET_ADMIN_USERNAME=${SUPERSET_ADMIN_USERNAME}
SUPERSET_ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD}
SUPERSET_ADMIN_FIRSTNAME=${SUPERSET_ADMIN_FIRSTNAME}
SUPERSET_ADMIN_LASTNAME=${SUPERSET_ADMIN_LASTNAME}
SUPERSET_ADMIN_EMAIL=${SUPERSET_ADMIN_EMAIL}

# Azure OAuth (from Key Vault)
AZURE_TENANT_ID=${AZURE_TENANT_ID}
AZURE_SUPERSET_CLIENT_ID=${AZURE_SUPERSET_CLIENT_ID}
AZURE_SUPERSET_CLIENT_SECRET=${AZURE_SUPERSET_CLIENT_SECRET}
AZURE_AIRFLOW_CLIENT_ID=${AZURE_AIRFLOW_CLIENT_ID}
AZURE_AIRFLOW_CLIENT_SECRET=${AZURE_AIRFLOW_CLIENT_SECRET}

# Airflow config
AIRFLOW_UID=50000
AIRFLOW_EXECUTOR=CeleryExecutor
AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
AIRFLOW__CORE__LOAD_EXAMPLES=false
AIRFLOW__CORE__PARALLELISM=32
AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=16
AIRFLOW__WEBSERVER__EXPOSE_CONFIG=false

# External ports
SUPERSET_EXTERNAL_PORT=8088
AIRFLOW_EXTERNAL_PORT=8080
HOP_EXTERNAL_PORT=8081
POSTGRES_EXTERNAL_PORT=5432
REDIS_EXTERNAL_PORT=6379

# Hop Server config (non-sensitive defaults)
HOP_SERVER_PORT=8081
HOP_SERVER_USER=cluster
HOP_SERVER_PASS=cluster
HOP_PROJECT_FOLDER=/opt/hop/projects
HOP_CONFIG_FOLDER=/opt/hop/config
HOP_SHARED_FOLDER=/shared/data
EOF

# Proteger .env file
chmod 600 .env

echo "✓ .env created with secrets from Key Vault"

# Build custom images se necessário
if [ ! "$(docker images -q superset-custom:latest 2> /dev/null)" ]; then
    echo ""
    echo "Building Superset custom image..."
    docker build -t superset-custom:latest ./superset
fi

# Iniciar infraestrutura
echo ""
echo "======================================================================"
echo " Starting Infrastructure"
echo "======================================================================"

# PostgreSQL e Redis primeiro
echo "Starting PostgreSQL and Redis..."
docker compose up -d postgres redis

echo "Waiting for databases to be healthy..."
sleep 15

# Executar migrations do Airflow
echo ""
echo "Running Airflow database migrations..."
docker run --rm \
    --network data-platform-network \
    -e "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD_URLENCODED}@postgres:5432/${POSTGRES_AIRFLOW_DB}" \
    apache/airflow:2.8.0-python3.11 \
    airflow db migrate

# Criar usuário admin Airflow
echo "Creating Airflow admin user..."
docker run --rm \
    --network data-platform-network \
    -e "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD_URLENCODED}@postgres:5432/${POSTGRES_AIRFLOW_DB}" \
    apache/airflow:2.8.0-python3.11 \
    airflow users create \
        --username "${AIRFLOW_ADMIN_USERNAME}" \
        --password "${AIRFLOW_ADMIN_PASSWORD}" \
        --firstname "${AIRFLOW_ADMIN_FIRSTNAME:-Admin}" \
        --lastname "${AIRFLOW_ADMIN_LASTNAME:-User}" \
        --role Admin \
        --email "${AIRFLOW_ADMIN_EMAIL:-admin@dataplatform.local}" || echo "User already exists"

# Iniciar todos os serviços
echo ""
echo "Starting all services..."
docker compose up -d

echo ""
echo "======================================================================"
echo " Deployment Complete!"
echo "======================================================================"
echo ""
echo "Services:"
echo "  Superset:  http://${PUBLIC_DOMAIN}:${SUPERSET_EXTERNAL_PORT}"
echo "  Airflow:   http://${PUBLIC_DOMAIN}:${AIRFLOW_EXTERNAL_PORT}"
echo "  Hop:       http://${PUBLIC_DOMAIN}:${HOP_EXTERNAL_PORT}"
echo ""
echo "Check status: docker compose ps"
echo "View logs:    docker compose logs -f <service>"
echo ""
